export const FETCH_ARTISTS = "FETCH_ARTISTS";
export const FETCH_FESTIVALS = "FETCH_FESTIVALS";
export const FETCH_FESTIVAL_ARTISTS = "FETCH_FESTIVAL_ARTISTS";
export const SAVE_CONTINENT = "SAVE_CONTINENT";
export const SAVE_YEAR = "SAVE_YEAR";
export const SELECT_FESTIVAL = "SELECT_FESTIVAL";
export const SAVE_JWT = "SAVE_JWT";
export const SAVE_SEARCH_INPUT = "SAVE_SEARCH_INPUT";
export const SAVE_FESTIVAL_LIST = "SAVE_FESTIVAL_LIST";
export const CREATE_PLAYLIST = "CREATE_PLAYLIST";
export const SAVE_FESTIVAL_COORDS = "SAVE_FESTIVAL_COORDS";
export const SAVE_CURRENT_COORDS = "SAVE_CURRENT_COORDS";


