export const FETCH_ARTISTS = "FETCH_ARTISTS";
export const FETCH_FESTIVALS = "FETCH_FESTIVALS";
export const FETCH_FESTIVAL_ARTISTS = "FETCH_FESTIVAL_ARTISTS";
export const SAVE_CONTINENT = "SAVE_CONTINENT";
export const SAVE_YEAR = "SAVE_YEAR";
export const SELECT_FESTIVAL = "SELECT_FESTIVAL";
