export const FETCH_ARTISTS = "FETCH_ARTISTS";
export const FETCH_FESTIVALS = "FETCH_FESTIVALS";

export const SAVE_CONTINENT = "SAVE_CONTINENT";
export const SAVE_YEAR = "SAVE_YEAR";
export const SAVE_SEARCH_INPUT = "SAVE_SEARCH_INPUT";
export const SAVE_FESTIVAL_COORDS = "SAVE_FESTIVAL_COORDS";
export const SAVE_CURRENT_COORDS = "SAVE_CURRENT_COORDS";


